import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const HEADER = "/* generated by scripts/build-tokens.mjs — do not edit */\n";
const BRANDS = ["business", "booking", "maps"];

const readJson = (p) => JSON.parse(readFileSync(join(ROOT, p), "utf8"));
const readText = (p) => readFileSync(join(ROOT, p), "utf8");

export function loadSources() {
  const schema = readJson("tokens/schema.json");
  const core = readJson("tokens/core.json");
  const brands = BRANDS.flatMap((name) => {
    try {
      const brand = readJson(`tokens/brands/${name}.json`);
      if (brand.brand !== name)
        throw new Error(`tokens/brands/${name}.json declares brand ${brand.brand}`);
      return [brand];
    } catch (error) {
      if (error.code === "ENOENT") return [];
      throw error;
    }
  });
  return { schema, core, brands };
}

const line = (name, value) => `  --${name}: ${value};`;
const block = (selector, lines) => `${selector} {\n${lines.join("\n")}\n}\n`;
const entries = (group) => Object.entries(group ?? {}).map(([k, v]) => line(k, v.$value));

export const themedRoles = (schema) => Object.values(schema.themed).flat();

function themeLines(schema, brand, theme) {
  const vars = brand.themes[theme];
  return themedRoles(schema).map((r) => line(r, vars[r].$value));
}

function baseLines(schema, brand) {
  const aliasLines = Object.entries(schema.aliases).map(([old, canon]) =>
    line(old, `var(--${canon})`),
  );
  return [
    ...themeLines(schema, brand, brand.defaultTheme),
    ...aliasLines,
    ...entries(brand.static),
  ];
}

export function brandCss(schema, brand) {
  const sel = `[data-brand="${brand.brand}"]`;
  const parts = [block(sel, baseLines(schema, brand))];
  for (const theme of schema.themes) {
    parts.push(block(`${sel}[data-theme="${theme}"]`, themeLines(schema, brand, theme)));
  }
  if (brand.followsSystem) {
    const inner = themeLines(schema, brand, "dark")
      .map((l) => `  ${l}`)
      .join("\n");
    parts.push(
      `@media (prefers-color-scheme: dark) {\n  ${sel}:not([data-theme="light"]) {\n${inner}\n  }\n}\n`,
    );
  }
  return HEADER + parts.join("\n");
}

export function coreCss(core) {
  return HEADER + block(":root", entries(core)) + "\n" + readText("tokens/core.static.css");
}

export function colorRoles(schema, brands) {
  const [sample] = brands;
  return themedRoles(schema).filter(
    (r) => sample.themes[sample.defaultTheme][r].$type === "color",
  );
}

export function themeCss(schema, brands) {
  return (
    HEADER +
    block(
      "@theme",
      colorRoles(schema, brands).map((r) => line(`color-${r}`, `var(--${r})`)),
    )
  );
}

export function tokensMd({ schema, brands }) {
  const row = (cells) => `| ${cells.join(" | ")} |`;
  const lines = [
    "# Токены контракта",
    "",
    "Источник истины — `tokens/brands/*.json`. Имена ролей = имена Figma Variables (`группа/роль` → `--группа-роль`).",
    "Контракт один на все бренды: бренд меняет значения, не имена.",
  ];

  const heads = brands.flatMap((b) => schema.themes.map((t) => `${b.brand} ${t}`));
  lines.push("", "## Роли по темам", "", row(["Роль", ...heads]), row(["---", ...heads.map(() => "---")]));
  for (const role of themedRoles(schema))
    lines.push(
      row([
        `\`--${role}\``,
        ...brands.flatMap((b) => schema.themes.map((t) => `\`${b.themes[t][role].$value}\``)),
      ]),
    );

  lines.push(
    "",
    "## Статические роли",
    "",
    row(["Роль", ...brands.map((b) => b.brand)]),
    row(["---", ...brands.map(() => "---")]),
  );
  for (const role of schema.static)
    lines.push(row([`\`--${role}\``, ...brands.map((b) => `\`${b.static[role].$value}\``)]));

  if (Object.keys(schema.aliases).length) {
    lines.push("", "## Алиасы (deprecated)", "");
    for (const [old, canon] of Object.entries(schema.aliases))
      lines.push(`- \`--${old}\` → \`--${canon}\``);
  }

  lines.push("", "## Ожидает значения от дизайнера", "");
  for (const b of brands) {
    if (b._pending) lines.push(`- ${b.brand}: ${b._pending}`);
    for (const t of schema.themes) {
      for (const [role, def] of Object.entries(b.themes[t])) {
        if (def.$description)
          lines.push(`- ${b.brand} ${t} \`--${role}\` = \`${def.$value}\` — ${def.$description}`);
      }
    }
    for (const [role, def] of Object.entries(b.static)) {
      if (def.$description)
        lines.push(`- ${b.brand} \`--${role}\` = \`${def.$value}\` — ${def.$description}`);
    }
  }
  lines.push(
    "",
    "## Как отдать значения",
    "",
    "1. В Figma Variables имена ролей совпадают с таблицей выше; коллекция на бренд, режим на тему.",
    "2. Значения переносятся в `tokens/brands/<brand>.json` литералами (без ссылок), PR в этот репозиторий.",
    "3. `npm run tokens:build` перегенерирует CSS и этот файл; `npm test` не пропустит пропущенную роль или `var()` в значении.",
    "",
  );
  return lines.join("\n");
}

export function build({ outStyles = "src/styles", outDocs = "docs" } = {}) {
  const src = loadSources();
  const written = [];
  const write = (rel, text) => {
    const abs = join(ROOT, rel);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, text);
    written.push(rel);
  };
  write(`${outStyles}/core.css`, coreCss(src.core));
  for (const brand of src.brands)
    write(`${outStyles}/brands/${brand.brand}.css`, brandCss(src.schema, brand));
  write(`${outStyles}/theme.css`, themeCss(src.schema, src.brands));
  write(`${outDocs}/tokens.md`, tokensMd(src));
  execFileSync("npx", ["--no-install", "prettier", "--write", ...written], {
    cwd: ROOT,
    stdio: "ignore",
  });
  return written;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) build();
