import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const HEADER = "/* generated by scripts/build-tokens.mjs — do not edit */\n";
const BRANDS = ["business", "booking", "maps"];

const readJson = (p) => JSON.parse(readFileSync(join(ROOT, p), "utf8"));
const readText = (p) => readFileSync(join(ROOT, p), "utf8");

export function loadSources() {
  const schema = readJson("tokens/schema.json");
  const core = readJson("tokens/core.json");
  const brands = BRANDS.flatMap((name) => {
    try {
      const brand = readJson(`tokens/brands/${name}.json`);
      if (brand.brand !== name)
        throw new Error(`tokens/brands/${name}.json declares brand ${brand.brand}`);
      return [brand];
    } catch (error) {
      if (error.code === "ENOENT") return [];
      throw error;
    }
  });
  return { schema, core, brands };
}

const line = (name, value) => `  --${name}: ${value};`;
const block = (selector, lines) => `${selector} {\n${lines.join("\n")}\n}\n`;
const entries = (group) => Object.entries(group ?? {}).map(([k, v]) => line(k, v.$value));

const override = (schema, brandName) =>
  schema.byBrand?.[brandName]?.replacesContract ? schema.byBrand[brandName] : null;

const themedGroups = (schema, brandName) => override(schema, brandName)?.themed ?? schema.themed;

export function themedRoles(schema, brandName) {
  return Object.values(themedGroups(schema, brandName)).flat();
}

export function staticRoles(schema, brandName) {
  return override(schema, brandName)?.static ?? schema.static;
}

export function aliasesFor(schema, brandName) {
  return override(schema, brandName)?.aliases ?? schema.aliases;
}

function themeLines(schema, brand, theme) {
  const vars = brand.themes[theme];
  return [
    ...themedRoles(schema, brand.brand).map((r) => line(r, vars[r].$value)),
    ...entries(brand.extras?.[theme]),
  ];
}

function baseLines(schema, brand) {
  const vars = brand.themes[brand.defaultTheme];
  const canonLines = themedRoles(schema, brand.brand).map((r) => line(r, vars[r].$value));
  const aliasLines = Object.entries(aliasesFor(schema, brand.brand)).map(([old, canon]) =>
    line(old, `var(--${canon})`),
  );
  const extraLines = entries(brand.extras?.[brand.defaultTheme]);
  return [
    ...canonLines,
    ...aliasLines,
    ...extraLines,
    ...entries(brand.static),
    ...entries(brand.kit),
  ];
}

export function brandCss(schema, brand) {
  const sel = `[data-brand="${brand.brand}"]`;
  const parts = [block(sel, baseLines(schema, brand))];
  for (const theme of schema.themes) {
    parts.push(block(`${sel}[data-theme="${theme}"]`, themeLines(schema, brand, theme)));
  }
  if (brand.followsSystem) {
    const inner = themeLines(schema, brand, "dark")
      .map((l) => `  ${l}`)
      .join("\n");
    parts.push(
      `@media (prefers-color-scheme: dark) {\n  ${sel}:not([data-theme="light"]) {\n${inner}\n  }\n}\n`,
    );
  }
  return HEADER + parts.join("\n");
}

export function coreCss(core) {
  return HEADER + block(":root", entries(core)) + "\n" + readText("tokens/core.static.css");
}

export function themeCss(schema, brands) {
  const roles = new Set();
  for (const brand of brands)
    for (const [group, list] of Object.entries(themedGroups(schema, brand.brand)))
      if (group !== "shadow") for (const role of list) roles.add(role);
  return (
    HEADER +
    block(
      "@theme",
      [...roles].map((r) => line(`color-${r}`, `var(--${r})`)),
    )
  );
}

export function tokensMd({ schema, brands }) {
  const row = (cells) => `| ${cells.join(" | ")} |`;
  const shared = brands.filter((b) => !override(schema, b.brand));
  const own = brands.filter((b) => override(schema, b.brand));
  const lines = [
    "# Токены контракта v2",
    "",
    "Источник истины — `tokens/brands/*.json`. Имена ролей = имена Figma Variables (`группа/роль` → `--группа-роль`).",
    "",
    "Бренд с собственным контрактом (`schema.byBrand.<brand>.replacesContract`) вынесен",
    "в отдельные таблицы: его роли приходят из своего файла Figma и с общим списком не пересекаются.",
  ];

  const themedTable = (title, group) => {
    if (!group.length) return;
    const heads = group.flatMap((b) => schema.themes.map((t) => `${b.brand} ${t}`));
    lines.push("", title, "", row(["Роль", ...heads]), row(["---", ...heads.map(() => "---")]));
    for (const role of themedRoles(schema, group[0].brand))
      lines.push(
        row([
          `\`--${role}\``,
          ...group.flatMap((b) => schema.themes.map((t) => `\`${b.themes[t][role].$value}\``)),
        ]),
      );
  };

  const staticTable = (title, group) => {
    if (!group.length) return;
    lines.push(
      "",
      title,
      "",
      row(["Роль", ...group.map((b) => b.brand)]),
      row(["---", ...group.map(() => "---")]),
    );
    for (const role of staticRoles(schema, group[0].brand))
      lines.push(row([`\`--${role}\``, ...group.map((b) => `\`${b.static[role].$value}\``)]));
  };

  themedTable("## Роли по темам — общий контракт", shared);
  for (const b of own) themedTable(`## Роли по темам — ${b.brand}`, [b]);
  staticTable("## Статические роли — общий контракт", shared);
  for (const b of own) staticTable(`## Статические роли — ${b.brand}`, [b]);

  lines.push("", "## Кит бренда", "");
  for (const b of brands) {
    if (!b.kit) continue;
    for (const [role, def] of Object.entries(b.kit))
      lines.push(`- ${b.brand}: \`--${role}\` = \`${def.$value}\``);
  }
  lines.push("", "## Алиасы (deprecated, удаление в 1.0.0)", "");
  if (shared.length) {
    lines.push(`- общий контракт (${shared.map((b) => b.brand).join(", ")}):`);
    for (const [old, canon] of Object.entries(schema.aliases))
      lines.push(`  - \`--${old}\` → \`--${canon}\``);
  }
  for (const b of own) {
    lines.push(`- ${b.brand}:`);
    for (const [old, canon] of Object.entries(aliasesFor(schema, b.brand)))
      lines.push(`  - \`--${old}\` → \`--${canon}\``);
  }
  lines.push("", "## Расширения брендов", "");
  for (const b of brands) {
    const names = new Set(schema.themes.flatMap((t) => Object.keys(b.extras?.[t] ?? {})));
    lines.push(`- ${b.brand}: ${[...names].map((n) => `\`--${n}\``).join(", ") || "нет"}`);
  }
  lines.push("", "## Ожидает значения от дизайнера", "");
  for (const b of brands) {
    for (const t of schema.themes) {
      for (const [role, def] of Object.entries(b.themes[t])) {
        if (def.$description)
          lines.push(`- ${b.brand} ${t} \`--${role}\` = \`${def.$value}\` — ${def.$description}`);
      }
    }
    for (const [role, def] of Object.entries(b.static)) {
      if (def.$description)
        lines.push(`- ${b.brand} \`--${role}\` = \`${def.$value}\` — ${def.$description}`);
    }
    for (const t of schema.themes) {
      for (const [role, def] of Object.entries(b.extras?.[t] ?? {})) {
        if (def.$description)
          lines.push(`- ${b.brand} ${t} \`--${role}\` = \`${def.$value}\` — ${def.$description}`);
      }
    }
  }
  lines.push(
    "",
    "## Как отдать значения",
    "",
    "1. В Figma Variables имена ролей совпадают с таблицей выше; коллекция на бренд, режим на тему.",
    "2. Значения переносятся в `tokens/brands/<brand>.json` литералами (без ссылок), PR в этот репозиторий.",
    "3. `npm run tokens:build` перегенерирует CSS и этот файл; `npm test` не пропустит пропущенную роль или `var()` в значении.",
    "",
  );
  return lines.join("\n");
}

export function build({ outStyles = "src/styles", outDocs = "docs" } = {}) {
  const src = loadSources();
  const written = [];
  const write = (rel, text) => {
    const abs = join(ROOT, rel);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, text);
    written.push(rel);
  };
  write(`${outStyles}/core.css`, coreCss(src.core));
  for (const brand of src.brands)
    write(`${outStyles}/brands/${brand.brand}.css`, brandCss(src.schema, brand));
  write(`${outStyles}/theme.css`, themeCss(src.schema, src.brands));
  write(`${outDocs}/tokens.md`, tokensMd(src));
  execFileSync("npx", ["--no-install", "prettier", "--write", ...written], {
    cwd: ROOT,
    stdio: "ignore",
  });
  return written;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) build();
